version: "3"

networks:
  fullstack:
    name: fullstack
    driver: bridge

services:
  email:
    container_name: email
    build:
      dockerfile: dockerfile-email
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - fullstack

  github-stack:
    container_name: github-stack
    build:
      dockerfile: dockerfile-github-stack
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - fullstack

  gateway:
    container_name: gateway
    build:
      dockerfile: dockerfile-gateway
    ports:
      - "3002:3002"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - fullstack

  redis:
    image: redis
    container_name: redis
    hostname: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - fullstack

  redis-commander:
    depends_on:
      - redis
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379 # note: this has to be the port the redis container exposes.
    ports:
      - "8081:8081"
    networks:
      - fullstack

  logger:
    container_name: logger
    build:
      dockerfile: dockerfile-logger
    ports:
      - "3003:3003"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - fullstack

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=SecurePostgresPassword2026
      - POSTGRES_USER=postgres
      - POSTGRES_DB=github_stack_db
      - POSTGRES_INITDB_ARGS=-c password_encryption=scram-sha-256
    volumes:
      - "./pgdata:/var/lib/postgresql/data2/pgdata"
    command: ["postgres", "-c", "password_encryption=scram-sha-256"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fullstack
